# 2.2 数据操作

In [1]:
import torch

torch.manual_seed(0)
torch.cuda.manual_seed(0)
print(torch.__version__)

1.9.1+cpu


## 2.2.1 创建`Tensor`

创建一个5x3的未初始化的`Tensor`：

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


创建一个5x3的随机初始化的`Tensor`:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])


In [18]:
x = torch.randn(5, 3)
print(x)

tensor([[ 1.9956, -0.9683, -0.7803],
        [-0.5713, -0.9645, -1.0204],
        [ 1.0309,  2.2084,  0.1380],
        [ 2.1086, -0.2239, -0.2360],
        [-0.3499, -1.9339,  0.3697]])


In [19]:
torch.randint(1,100,(5,3))

tensor([[ 3, 76, 68],
        [ 7, 41,  4],
        [ 4, 64, 83],
        [40, 39, 53],
        [35, 76, 32]])

In [16]:
torch.randn??

In [20]:
torch.rand??

In [12]:
torch.randint??

# randint(low=0, high, size)

创建一个5x3的long型全0的`Tensor`:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接根据数据创建:

In [21]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


还可以通过现有的`Tensor`来创建，此方法会默认重用输入`Tensor`的一些属性，例如数据类型，除非自定义数据类型。

In [33]:
x = x.new_ones(5, 3, dtype=torch.float64)      # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 指定新的数据类型
print(x)                                    

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2692, -0.0630,  0.0084],
        [ 0.9664,  0.7486,  1.2709],
        [ 0.2109,  1.5359, -2.1960],
        [-0.4223, -0.1316,  0.1957],
        [-1.0772,  0.4173, -0.1003]])


我们可以通过`shape`或者`size()`来获取`Tensor`的形状:

In [34]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


> 注意：返回的torch.Size其实就是一个tuple, 支持所有tuple的操作。

## 2.2.2 操作
### 算术操作
* **加法形式一**

In [35]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.3880,  0.6854,  0.0545],
        [ 0.9858,  0.7628,  1.6695],
        [ 1.0471,  1.5626, -1.2804],
        [-0.1224,  0.5148,  0.7185],
        [-1.0281,  1.3320,  0.6689]])


* **加法形式二**

In [36]:
print(torch.add(x, y))

tensor([[ 0.3880,  0.6854,  0.0545],
        [ 0.9858,  0.7628,  1.6695],
        [ 1.0471,  1.5626, -1.2804],
        [-0.1224,  0.5148,  0.7185],
        [-1.0281,  1.3320,  0.6689]])


In [40]:
result = torch.empty(5, 3)
result

tensor([[3.4899e-39, 9.2755e-39, 8.7245e-39],
        [7.8980e-39, 9.2755e-39, 7.3469e-39],
        [1.0194e-38, 8.7245e-39, 6.2449e-39],
        [8.7245e-39, 6.1531e-39, 7.6225e-39],
        [5.0511e-39, 4.4082e-39, 7.6225e-39]])

In [50]:
torch.add(x, y)

tensor([[ 0.3880,  0.6854,  0.0545],
        [ 0.9858,  0.7628,  1.6695],
        [ 1.0471,  1.5626, -1.2804],
        [-0.1224,  0.5148,  0.7185],
        [-1.0281,  1.3320,  0.6689]])

In [51]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3880,  0.6854,  0.0545],
        [ 0.9858,  0.7628,  1.6695],
        [ 1.0471,  1.5626, -1.2804],
        [-0.1224,  0.5148,  0.7185],
        [-1.0281,  1.3320,  0.6689]])


In [49]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3880,  0.6854,  0.0545],
        [ 0.9858,  0.7628,  1.6695],
        [ 1.0471,  1.5626, -1.2804],
        [-0.1224,  0.5148,  0.7185],
        [-1.0281,  1.3320,  0.6689]])


In [52]:
torch.add??

* **加法形式三、inplace**

In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.3967,  1.0892,  0.4369],
        [ 1.6995,  2.0453,  0.6539],
        [-0.1553,  3.7016, -0.3599],
        [ 0.7536,  0.0870,  1.2274],
        [ 2.5046, -0.1913,  0.4760]])


> **注：PyTorch操作inplace版本都有后缀"_", 例如`x.copy_(y), x.t_()`**

### 索引
我们还可以使用类似NumPy的索引操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。** 

In [53]:
print(x)
y = x[0, :]
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了

tensor([[ 0.2692, -0.0630,  0.0084],
        [ 0.9664,  0.7486,  1.2709],
        [ 0.2109,  1.5359, -2.1960],
        [-0.4223, -0.1316,  0.1957],
        [-1.0772,  0.4173, -0.1003]])
tensor([1.2692, 0.9370, 1.0084])
tensor([1.2692, 0.9370, 1.0084])


In [54]:
print(x)

tensor([[ 1.2692,  0.9370,  1.0084],
        [ 0.9664,  0.7486,  1.2709],
        [ 0.2109,  1.5359, -2.1960],
        [-0.4223, -0.1316,  0.1957],
        [-1.0772,  0.4173, -0.1003]])


### 改变形状
用`view()`来改变`Tensor`的形状：

In [55]:
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


**注意`view()`返回的新tensor与源tensor共享内存，也即更改其中的一个，另外一个也会跟着改变。**

In [56]:
print(x)
x += 1
print(x)
print(y) # 也加了1

tensor([[ 1.2692,  0.9370,  1.0084],
        [ 0.9664,  0.7486,  1.2709],
        [ 0.2109,  1.5359, -2.1960],
        [-0.4223, -0.1316,  0.1957],
        [-1.0772,  0.4173, -0.1003]])
tensor([[ 2.2692,  1.9370,  2.0084],
        [ 1.9664,  1.7486,  2.2709],
        [ 1.2109,  2.5359, -1.1960],
        [ 0.5777,  0.8684,  1.1957],
        [-0.0772,  1.4173,  0.8997]])
tensor([ 2.2692,  1.9370,  2.0084,  1.9664,  1.7486,  2.2709,  1.2109,  2.5359,
        -1.1960,  0.5777,  0.8684,  1.1957, -0.0772,  1.4173,  0.8997])


如果不想共享内存，推荐先用`clone`创造一个副本然后再使用`view`。

In [57]:
print(x)
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 2.2692,  1.9370,  2.0084],
        [ 1.9664,  1.7486,  2.2709],
        [ 1.2109,  2.5359, -1.1960],
        [ 0.5777,  0.8684,  1.1957],
        [-0.0772,  1.4173,  0.8997]])
tensor([[ 1.2692,  0.9370,  1.0084],
        [ 0.9664,  0.7486,  1.2709],
        [ 0.2109,  1.5359, -2.1960],
        [-0.4223, -0.1316,  0.1957],
        [-1.0772,  0.4173, -0.1003]])
tensor([ 2.2692,  1.9370,  2.0084,  1.9664,  1.7486,  2.2709,  1.2109,  2.5359,
        -1.1960,  0.5777,  0.8684,  1.1957, -0.0772,  1.4173,  0.8997])


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [58]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.2897])
1.2897011041641235


## 2.2.3 广播机制

In [59]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 2.2.4 运算的内存开销

In [63]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y += x
print(id(y) == id_before)

True


In [64]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


In [65]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [66]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before)

True


In [67]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
# torch.add(x, y, out=y) # y += x, y.add_(x)
y.add_(x)
print(id(y) == id_before)

True


## 2.2.5 `Tensor`和NumPy相互转换
**`numpy()`和`from_numpy()`这两个函数产生的`Tensor`和NumPy array实际是使用的相同的内存，改变其中一个时另一个也会改变！！！**
### `Tensor`转NumPy

In [21]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### NumPy数组转`Tensor`

In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


直接用`torch.tensor()`将NumPy数组转换成`Tensor`，该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存。

In [23]:
# 用torch.tensor()转换时不会共享内存
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## 2.2.6 `Tensor` on GPU

In [68]:
x

tensor([1, 2])

In [69]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型

**我来啦！**